#!/bin/bash

# make the data directory if it doesn't already exist
mkdir -p data

python -OO blocks.py
echo "blocks written"
python -OO txs.py
echo "transactions written"
python -OO inputs.py
echo "inputs written"
python -OO outputs.py
echo "outputs written"
python -OO users.py
echo "classic user heuristic finished"
python -OO heurusers.py
echo "new user heuristic finished"
